mkdir brackets
cd brackets
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/replicator.php
php replicator.php
cd elements
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/arduino-bracket.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/arduino-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/cable-cleat.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/cable-cleat.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/circuit-playground-express-wood-bracket.3mf
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/circuit-playground-express-wood-bracket.SLDDRW
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/circuit-playground-express-wood-bracket.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/circuit-playground-express-wood-bracket.STEP
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/circuit-playground-express-wood-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi-board-simple.SLDDRW
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi-board-simple.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi-board-simple.pdf
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi4-wood-bracket.SLDDRW
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi4-wood-bracket.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi4-wood-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/pi4-wood-bracket.pdf
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/stemma-knob-wood-bracket.SLDDRW
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/stemma-knob-wood-bracket.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/stemma-knob-wood-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/sunfounder-screen-wood-bracket.SLDPRT
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/elements/sunfounder-screen-wood-bracket.STL
cd ../images
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/3d-printer.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/4-40-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/4-40inserts.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/M2point5-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/M2point5inserts.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/M5-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/arduino-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/cable-cleat-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/circuit-playground-express-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/insert-tool.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/pi4-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/qrcode-page.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/qrcode.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/stemma-knob-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/sunfounder-screen-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/images/woodscrews.png
cd ..
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/index.html -O index.html
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/replicator.sh -O replicator.sh
wget https://raw.githubusercontent.com/LafeLabs/network/main/brackets/README.md -O README.md
cd ..
