mkdir hiphopbaby
cd hiphopbaby
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/album/replicator.php
php replicator.php
cd tracks
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/The%20Last%20Poet%20-%20Hip%20Hop%20Baby%20-%2001%20Intro%20feat.%20Who%27s%20Los.mp3
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/The%20Last%20Poet%20-%20Hip%20Hop%20Baby%20-%2002%20Freeway%20feat.%20Who%27s%20Los.mp3
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/The%20Last%20Poet%20-%20Hip%20Hop%20Baby%20-%2003%20F.A.R.%20Fake%20Ass%20Rapper%20Skit%20feat.%20The%20Last%20Lightskin.mp3
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/The%20Last%20Poet%20-%20Hip%20Hop%20Baby%20-%2004%20Don%27t%20Fuck%20With%20Me.mp3
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/The%20Last%20Poet%20-%20Hip%20Hop%20Baby%20-%2005%20Hip%20Hop%20Baby.mp3
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/tracks/beatin%20up%20a%20bitch_mixdown.mp3
cd ../images
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/images/cover.png
cd ..
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/index.html
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/replicator.sh
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/thelastpoet/hiphopbaby/README.md
cd ..
