mkdir mynewset
cd mynewset
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/replicator.php
php replicator.php
cd elements
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/elements/2x4bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/elements/circuit-playground-express-wood-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/elements/flat-bracket.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/elements/pi4-wood-bracket-3.STL
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/elements/sunfounder-screen-wood-bracket.STL
cd ../images
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/2x4bracket.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/4-40-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/M2.5-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/M4-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/ac-line-extension-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/aux-cables-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/barrel-splitter.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/bluetooth-speakers-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/buck-converter.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/circuit-playground-express-kit-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/keyboard-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/microphone-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/mouse-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/number-4-wood-screws.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/pi-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/pi-screen-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/pi4-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/power-station-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/sdr-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/sloanslake-ebike-2.jpeg
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/sloanslake-ebike.jpeg
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/solar-dc-extension-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/solar-panel-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/sunfounder-screen-wood-bracket-stl.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/thumb-drive-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/usb-c-power.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/white-usb-light-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/wifi-amazon.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/images/wifi-antenna-amazon.png
cd ..
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/index.html -O index.html
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/replicator.sh -O replicator.sh
wget https://raw.githubusercontent.com/LafeLabs/network/main/terminal/README.md -O README.md
cd ..
