mkdir myalbum
cd myalbum
wget https://raw.githubusercontent.com/LafeLabs/network/main/music/album/replicator.php
php replicator.php
cd tracks
cd ../images
wget https://raw.githubusercontent.com/LafeLabs/network/main/page/images/qrcode-page.png
wget https://raw.githubusercontent.com/LafeLabs/network/main/page/images/qrcode.png
cd ..
wget https://raw.githubusercontent.com/LafeLabs/network/main/page/index.html
wget https://raw.githubusercontent.com/LafeLabs/network/main/page/replicator.sh
wget https://raw.githubusercontent.com/LafeLabs/network/main/page/README.md
cd ..
